// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package org.generic;

public interface CreateUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Success status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.Success status = 1;</code>
   * @return The status.
   */
  org.generic.Success getStatus();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string accessToken = 3;</code>
   * @return The accessToken.
   */
  java.lang.String getAccessToken();
  /**
   * <code>string accessToken = 3;</code>
   * @return The bytes for accessToken.
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <code>string refreshToken = 4;</code>
   * @return The refreshToken.
   */
  java.lang.String getRefreshToken();
  /**
   * <code>string refreshToken = 4;</code>
   * @return The bytes for refreshToken.
   */
  com.google.protobuf.ByteString
      getRefreshTokenBytes();
}
