// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package org.generic;

public final class Entity {
  private Entity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResetUsernameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResetUsernameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResetPasswordRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResetPasswordRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UnauthenticatedUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UnauthenticatedUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserValidityCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserValidityCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TokenIssueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TokenIssueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TokenIssueRequest_AuthenticatedUserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TokenIssueRequest_AuthenticatedUserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TokenRevokeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TokenRevokeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TokenIssueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TokenIssueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TokenRevokeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TokenRevokeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014entity.proto\"7\n\021CreateUserRequest\022\020\n\010u" +
      "sername\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"=\n\024Reset" +
      "UsernameRequest\022\020\n\010username\030\001 \001(\t\022\023\n\013new" +
      "Username\030\002 \001(\t\":\n\024ResetPasswordRequest\022\020" +
      "\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"@\n\032Un" +
      "authenticatedUserRequest\022\020\n\010username\030\001 \001" +
      "(\t\022\020\n\010password\030\002 \001(\t\"^\n\030UserValidityChec" +
      "kRequest\022\023\n\013accessToken\030\001 \001(\t\022 \n\010provide" +
      "r\030\002 \001(\0162\t.ProviderH\000\210\001\001B\013\n\t_provider\"\316\001\n" +
      "\021TokenIssueRequest\0226\n\017unauthenticated\030\001 " +
      "\001(\0132\033.UnauthenticatedUserRequestH\000\022D\n\rau" +
      "thenticated\030\002 \001(\0132+.TokenIssueRequest.Au" +
      "thenticatedUserRequestH\000\0320\n\030Authenticate" +
      "dUserRequest\022\024\n\014refreshToken\030\001 \001(\tB\t\n\007re" +
      "quest\"&\n\022TokenRevokeRequest\022\020\n\010username\030" +
      "\001 \001(\t\"7\n\rErrorResponse\022\025\n\005error\030\001 \001(\0162\006." +
      "Error\022\017\n\007message\030\002 \001(\t\"j\n\022CreateUserResp" +
      "onse\022\030\n\006status\030\001 \001(\0162\010.Success\022\017\n\007messag" +
      "e\030\002 \001(\t\022\023\n\013accessToken\030\003 \001(\t\022\024\n\014refreshT" +
      "oken\030\004 \001(\t\":\n\rResetResponse\022\030\n\006status\030\001 " +
      "\001(\0162\010.Success\022\017\n\007message\030\002 \001(\t\"c\n\014AuthRe" +
      "sponse\022\030\n\006status\030\001 \001(\0162\010.Success\022\017\n\007mess" +
      "age\030\002 \001(\t\022\030\n\013accessToken\030\003 \001(\tH\000\210\001\001B\016\n\014_" +
      "accessToken\"\200\001\n\022TokenIssueResponse\022\030\n\006st" +
      "atus\030\001 \001(\0162\010.Success\022\017\n\007message\030\002 \001(\t\022\023\n" +
      "\013accessToken\030\003 \001(\t\022\031\n\014refreshToken\030\004 \001(\t" +
      "H\000\210\001\001B\017\n\r_refreshToken\"@\n\023TokenRevokeRes" +
      "ponse\022\030\n\006status\030\001 \001(\0162\010.Success\022\017\n\007messa" +
      "ge\030\002 \001(\t*\356\002\n\005Error\022\027\n\023USER_ALREADY_EXIST" +
      "S\020\000\022\036\n\032WRONG_USERNAME_OR_PASSWORD\020\001\022\024\n\020P" +
      "ASSWORD_EXPIRED\020\002\022&\n\"PASSWORD_IDENTICAL_" +
      "TO_PREVIOUS_SET\020\003\022$\n RESET_REQUEST_BEFOR" +
      "E_BUFFER_TIME\020\004\022\030\n\024ACCESS_TOKEN_EXPIRED\020" +
      "\005\022\030\n\024INVALID_ACCESS_TOKEN\020\006\022\031\n\025REFRESH_T" +
      "OKEN_EXPIRED\020\007\022\031\n\025INVALID_REFRESH_TOKEN\020" +
      "\010\022&\n\"INVALID_REFRESH_TOKEN_ISSUE_POLICY\020" +
      "\t\022\033\n\027TOO_MANY_LOGIN_ATTEMPTS\020\n\022\031\n\025INTERN" +
      "AL_SERVER_ERROR\020\013*\272\001\n\007Success\022\024\n\020NEW_USE" +
      "R_CREATED\020\000\022!\n\035USERNAME_CHANGED_SUCCESSF" +
      "ULLY\020\001\022\037\n\033PASSWORD_RESET_SUCCESSFULLY\020\002\022" +
      "\026\n\022AUTHENTICATED_USER\020\003\022\035\n\031TOKEN_ISSUED_" +
      "SUCCESSFULLY\020\004\022\036\n\032TOKEN_REVOKED_SUCCESSF" +
      "ULLY\020\005*\026\n\010Provider\022\n\n\006GOOGLE\020\000B\022\n\013org.ge" +
      "nericP\001\240\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CreateUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateUserRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_ResetUsernameRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResetUsernameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResetUsernameRequest_descriptor,
        new java.lang.String[] { "Username", "NewUsername", });
    internal_static_ResetPasswordRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ResetPasswordRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResetPasswordRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_UnauthenticatedUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UnauthenticatedUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UnauthenticatedUserRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_UserValidityCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_UserValidityCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserValidityCheckRequest_descriptor,
        new java.lang.String[] { "AccessToken", "Provider", "Provider", });
    internal_static_TokenIssueRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_TokenIssueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TokenIssueRequest_descriptor,
        new java.lang.String[] { "Unauthenticated", "Authenticated", "Request", });
    internal_static_TokenIssueRequest_AuthenticatedUserRequest_descriptor =
      internal_static_TokenIssueRequest_descriptor.getNestedTypes().get(0);
    internal_static_TokenIssueRequest_AuthenticatedUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TokenIssueRequest_AuthenticatedUserRequest_descriptor,
        new java.lang.String[] { "RefreshToken", });
    internal_static_TokenRevokeRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_TokenRevokeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TokenRevokeRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_ErrorResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_ErrorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrorResponse_descriptor,
        new java.lang.String[] { "Error", "Message", });
    internal_static_CreateUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_CreateUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateUserResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "AccessToken", "RefreshToken", });
    internal_static_ResetResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ResetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResetResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_AuthResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_AuthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "AccessToken", "AccessToken", });
    internal_static_TokenIssueResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_TokenIssueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TokenIssueResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "AccessToken", "RefreshToken", "RefreshToken", });
    internal_static_TokenRevokeResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_TokenRevokeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TokenRevokeResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
