// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package org.generic;

public interface ErrorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ErrorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Error error = 1;</code>
   * @return The enum numeric value on the wire for error.
   */
  int getErrorValue();
  /**
   * <code>.Error error = 1;</code>
   * @return The error.
   */
  org.generic.Error getError();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
