// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package org.generic;

public interface ResetUsernameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResetUsernameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string newUsername = 2;</code>
   * @return The newUsername.
   */
  java.lang.String getNewUsername();
  /**
   * <code>string newUsername = 2;</code>
   * @return The bytes for newUsername.
   */
  com.google.protobuf.ByteString
      getNewUsernameBytes();
}
