// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package org.generic;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rservice.proto\032\014entity.proto2\334\002\n\004Auth\0225" +
      "\n\ncreateUser\022\022.CreateUserRequest\032\023.Creat" +
      "eUserResponse\0226\n\rresetUsername\022\025.ResetUs" +
      "ernameRequest\032\016.ResetResponse\0226\n\rresetPa" +
      "ssword\022\025.ResetPasswordRequest\032\016.ResetRes" +
      "ponse\022<\n\020authenticateUser\022\031.UserValidity" +
      "CheckRequest\032\r.AuthResponse\0225\n\nissueToke" +
      "n\022\022.TokenIssueRequest\032\023.TokenIssueRespon" +
      "se\0228\n\013revokeToken\022\023.TokenRevokeRequest\032\024" +
      ".TokenRevokeResponseB\022\n\013org.genericP\001\240\001\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.generic.Entity.getDescriptor(),
        });
    org.generic.Entity.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
