// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package org.generic;

/**
 * Protobuf type {@code TokenIssueRequest}
 */
public final class TokenIssueRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TokenIssueRequest)
    TokenIssueRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TokenIssueRequest.newBuilder() to construct.
  private TokenIssueRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TokenIssueRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TokenIssueRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.generic.Entity.internal_static_TokenIssueRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.generic.Entity.internal_static_TokenIssueRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.generic.TokenIssueRequest.class, org.generic.TokenIssueRequest.Builder.class);
  }

  public interface AuthenticatedUserRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TokenIssueRequest.AuthenticatedUserRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string refreshToken = 1;</code>
     * @return The refreshToken.
     */
    java.lang.String getRefreshToken();
    /**
     * <code>string refreshToken = 1;</code>
     * @return The bytes for refreshToken.
     */
    com.google.protobuf.ByteString
        getRefreshTokenBytes();
  }
  /**
   * Protobuf type {@code TokenIssueRequest.AuthenticatedUserRequest}
   */
  public static final class AuthenticatedUserRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TokenIssueRequest.AuthenticatedUserRequest)
      AuthenticatedUserRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AuthenticatedUserRequest.newBuilder() to construct.
    private AuthenticatedUserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AuthenticatedUserRequest() {
      refreshToken_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AuthenticatedUserRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.generic.Entity.internal_static_TokenIssueRequest_AuthenticatedUserRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.generic.Entity.internal_static_TokenIssueRequest_AuthenticatedUserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.generic.TokenIssueRequest.AuthenticatedUserRequest.class, org.generic.TokenIssueRequest.AuthenticatedUserRequest.Builder.class);
    }

    public static final int REFRESHTOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object refreshToken_;
    /**
     * <code>string refreshToken = 1;</code>
     * @return The refreshToken.
     */
    @java.lang.Override
    public java.lang.String getRefreshToken() {
      java.lang.Object ref = refreshToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refreshToken_ = s;
        return s;
      }
    }
    /**
     * <code>string refreshToken = 1;</code>
     * @return The bytes for refreshToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRefreshTokenBytes() {
      java.lang.Object ref = refreshToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refreshToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(refreshToken_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, refreshToken_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(refreshToken_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, refreshToken_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.generic.TokenIssueRequest.AuthenticatedUserRequest)) {
        return super.equals(obj);
      }
      org.generic.TokenIssueRequest.AuthenticatedUserRequest other = (org.generic.TokenIssueRequest.AuthenticatedUserRequest) obj;

      if (!getRefreshToken()
          .equals(other.getRefreshToken())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REFRESHTOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getRefreshToken().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.generic.TokenIssueRequest.AuthenticatedUserRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.generic.TokenIssueRequest.AuthenticatedUserRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.generic.TokenIssueRequest.AuthenticatedUserRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.generic.TokenIssueRequest.AuthenticatedUserRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.generic.TokenIssueRequest.AuthenticatedUserRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.generic.TokenIssueRequest.AuthenticatedUserRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.generic.TokenIssueRequest.AuthenticatedUserRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.generic.TokenIssueRequest.AuthenticatedUserRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.generic.TokenIssueRequest.AuthenticatedUserRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.generic.TokenIssueRequest.AuthenticatedUserRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.generic.TokenIssueRequest.AuthenticatedUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.generic.TokenIssueRequest.AuthenticatedUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.generic.TokenIssueRequest.AuthenticatedUserRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TokenIssueRequest.AuthenticatedUserRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TokenIssueRequest.AuthenticatedUserRequest)
        org.generic.TokenIssueRequest.AuthenticatedUserRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.generic.Entity.internal_static_TokenIssueRequest_AuthenticatedUserRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.generic.Entity.internal_static_TokenIssueRequest_AuthenticatedUserRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.generic.TokenIssueRequest.AuthenticatedUserRequest.class, org.generic.TokenIssueRequest.AuthenticatedUserRequest.Builder.class);
      }

      // Construct using org.generic.TokenIssueRequest.AuthenticatedUserRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        refreshToken_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.generic.Entity.internal_static_TokenIssueRequest_AuthenticatedUserRequest_descriptor;
      }

      @java.lang.Override
      public org.generic.TokenIssueRequest.AuthenticatedUserRequest getDefaultInstanceForType() {
        return org.generic.TokenIssueRequest.AuthenticatedUserRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.generic.TokenIssueRequest.AuthenticatedUserRequest build() {
        org.generic.TokenIssueRequest.AuthenticatedUserRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.generic.TokenIssueRequest.AuthenticatedUserRequest buildPartial() {
        org.generic.TokenIssueRequest.AuthenticatedUserRequest result = new org.generic.TokenIssueRequest.AuthenticatedUserRequest(this);
        result.refreshToken_ = refreshToken_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.generic.TokenIssueRequest.AuthenticatedUserRequest) {
          return mergeFrom((org.generic.TokenIssueRequest.AuthenticatedUserRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.generic.TokenIssueRequest.AuthenticatedUserRequest other) {
        if (other == org.generic.TokenIssueRequest.AuthenticatedUserRequest.getDefaultInstance()) return this;
        if (!other.getRefreshToken().isEmpty()) {
          refreshToken_ = other.refreshToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                refreshToken_ = input.readStringRequireUtf8();

                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object refreshToken_ = "";
      /**
       * <code>string refreshToken = 1;</code>
       * @return The refreshToken.
       */
      public java.lang.String getRefreshToken() {
        java.lang.Object ref = refreshToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          refreshToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string refreshToken = 1;</code>
       * @return The bytes for refreshToken.
       */
      public com.google.protobuf.ByteString
          getRefreshTokenBytes() {
        java.lang.Object ref = refreshToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          refreshToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string refreshToken = 1;</code>
       * @param value The refreshToken to set.
       * @return This builder for chaining.
       */
      public Builder setRefreshToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        refreshToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string refreshToken = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRefreshToken() {
        
        refreshToken_ = getDefaultInstance().getRefreshToken();
        onChanged();
        return this;
      }
      /**
       * <code>string refreshToken = 1;</code>
       * @param value The bytes for refreshToken to set.
       * @return This builder for chaining.
       */
      public Builder setRefreshTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        refreshToken_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TokenIssueRequest.AuthenticatedUserRequest)
    }

    // @@protoc_insertion_point(class_scope:TokenIssueRequest.AuthenticatedUserRequest)
    private static final org.generic.TokenIssueRequest.AuthenticatedUserRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.generic.TokenIssueRequest.AuthenticatedUserRequest();
    }

    public static org.generic.TokenIssueRequest.AuthenticatedUserRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthenticatedUserRequest>
        PARSER = new com.google.protobuf.AbstractParser<AuthenticatedUserRequest>() {
      @java.lang.Override
      public AuthenticatedUserRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AuthenticatedUserRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuthenticatedUserRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.generic.TokenIssueRequest.AuthenticatedUserRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int requestCase_ = 0;
  private java.lang.Object request_;
  public enum RequestCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    UNAUTHENTICATED(1),
    AUTHENTICATED(2),
    REQUEST_NOT_SET(0);
    private final int value;
    private RequestCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestCase valueOf(int value) {
      return forNumber(value);
    }

    public static RequestCase forNumber(int value) {
      switch (value) {
        case 1: return UNAUTHENTICATED;
        case 2: return AUTHENTICATED;
        case 0: return REQUEST_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public RequestCase
  getRequestCase() {
    return RequestCase.forNumber(
        requestCase_);
  }

  public static final int UNAUTHENTICATED_FIELD_NUMBER = 1;
  /**
   * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
   * @return Whether the unauthenticated field is set.
   */
  @java.lang.Override
  public boolean hasUnauthenticated() {
    return requestCase_ == 1;
  }
  /**
   * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
   * @return The unauthenticated.
   */
  @java.lang.Override
  public org.generic.UnauthenticatedUserRequest getUnauthenticated() {
    if (requestCase_ == 1) {
       return (org.generic.UnauthenticatedUserRequest) request_;
    }
    return org.generic.UnauthenticatedUserRequest.getDefaultInstance();
  }
  /**
   * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
   */
  @java.lang.Override
  public org.generic.UnauthenticatedUserRequestOrBuilder getUnauthenticatedOrBuilder() {
    if (requestCase_ == 1) {
       return (org.generic.UnauthenticatedUserRequest) request_;
    }
    return org.generic.UnauthenticatedUserRequest.getDefaultInstance();
  }

  public static final int AUTHENTICATED_FIELD_NUMBER = 2;
  /**
   * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
   * @return Whether the authenticated field is set.
   */
  @java.lang.Override
  public boolean hasAuthenticated() {
    return requestCase_ == 2;
  }
  /**
   * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
   * @return The authenticated.
   */
  @java.lang.Override
  public org.generic.TokenIssueRequest.AuthenticatedUserRequest getAuthenticated() {
    if (requestCase_ == 2) {
       return (org.generic.TokenIssueRequest.AuthenticatedUserRequest) request_;
    }
    return org.generic.TokenIssueRequest.AuthenticatedUserRequest.getDefaultInstance();
  }
  /**
   * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
   */
  @java.lang.Override
  public org.generic.TokenIssueRequest.AuthenticatedUserRequestOrBuilder getAuthenticatedOrBuilder() {
    if (requestCase_ == 2) {
       return (org.generic.TokenIssueRequest.AuthenticatedUserRequest) request_;
    }
    return org.generic.TokenIssueRequest.AuthenticatedUserRequest.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestCase_ == 1) {
      output.writeMessage(1, (org.generic.UnauthenticatedUserRequest) request_);
    }
    if (requestCase_ == 2) {
      output.writeMessage(2, (org.generic.TokenIssueRequest.AuthenticatedUserRequest) request_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (org.generic.UnauthenticatedUserRequest) request_);
    }
    if (requestCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (org.generic.TokenIssueRequest.AuthenticatedUserRequest) request_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.generic.TokenIssueRequest)) {
      return super.equals(obj);
    }
    org.generic.TokenIssueRequest other = (org.generic.TokenIssueRequest) obj;

    if (!getRequestCase().equals(other.getRequestCase())) return false;
    switch (requestCase_) {
      case 1:
        if (!getUnauthenticated()
            .equals(other.getUnauthenticated())) return false;
        break;
      case 2:
        if (!getAuthenticated()
            .equals(other.getAuthenticated())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (requestCase_) {
      case 1:
        hash = (37 * hash) + UNAUTHENTICATED_FIELD_NUMBER;
        hash = (53 * hash) + getUnauthenticated().hashCode();
        break;
      case 2:
        hash = (37 * hash) + AUTHENTICATED_FIELD_NUMBER;
        hash = (53 * hash) + getAuthenticated().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.generic.TokenIssueRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.generic.TokenIssueRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.generic.TokenIssueRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.generic.TokenIssueRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.generic.TokenIssueRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.generic.TokenIssueRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.generic.TokenIssueRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.generic.TokenIssueRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.generic.TokenIssueRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.generic.TokenIssueRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.generic.TokenIssueRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.generic.TokenIssueRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.generic.TokenIssueRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TokenIssueRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TokenIssueRequest)
      org.generic.TokenIssueRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.generic.Entity.internal_static_TokenIssueRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.generic.Entity.internal_static_TokenIssueRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.generic.TokenIssueRequest.class, org.generic.TokenIssueRequest.Builder.class);
    }

    // Construct using org.generic.TokenIssueRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (unauthenticatedBuilder_ != null) {
        unauthenticatedBuilder_.clear();
      }
      if (authenticatedBuilder_ != null) {
        authenticatedBuilder_.clear();
      }
      requestCase_ = 0;
      request_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.generic.Entity.internal_static_TokenIssueRequest_descriptor;
    }

    @java.lang.Override
    public org.generic.TokenIssueRequest getDefaultInstanceForType() {
      return org.generic.TokenIssueRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.generic.TokenIssueRequest build() {
      org.generic.TokenIssueRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.generic.TokenIssueRequest buildPartial() {
      org.generic.TokenIssueRequest result = new org.generic.TokenIssueRequest(this);
      if (requestCase_ == 1) {
        if (unauthenticatedBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = unauthenticatedBuilder_.build();
        }
      }
      if (requestCase_ == 2) {
        if (authenticatedBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = authenticatedBuilder_.build();
        }
      }
      result.requestCase_ = requestCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.generic.TokenIssueRequest) {
        return mergeFrom((org.generic.TokenIssueRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.generic.TokenIssueRequest other) {
      if (other == org.generic.TokenIssueRequest.getDefaultInstance()) return this;
      switch (other.getRequestCase()) {
        case UNAUTHENTICATED: {
          mergeUnauthenticated(other.getUnauthenticated());
          break;
        }
        case AUTHENTICATED: {
          mergeAuthenticated(other.getAuthenticated());
          break;
        }
        case REQUEST_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getUnauthenticatedFieldBuilder().getBuilder(),
                  extensionRegistry);
              requestCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getAuthenticatedFieldBuilder().getBuilder(),
                  extensionRegistry);
              requestCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int requestCase_ = 0;
    private java.lang.Object request_;
    public RequestCase
        getRequestCase() {
      return RequestCase.forNumber(
          requestCase_);
    }

    public Builder clearRequest() {
      requestCase_ = 0;
      request_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        org.generic.UnauthenticatedUserRequest, org.generic.UnauthenticatedUserRequest.Builder, org.generic.UnauthenticatedUserRequestOrBuilder> unauthenticatedBuilder_;
    /**
     * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
     * @return Whether the unauthenticated field is set.
     */
    @java.lang.Override
    public boolean hasUnauthenticated() {
      return requestCase_ == 1;
    }
    /**
     * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
     * @return The unauthenticated.
     */
    @java.lang.Override
    public org.generic.UnauthenticatedUserRequest getUnauthenticated() {
      if (unauthenticatedBuilder_ == null) {
        if (requestCase_ == 1) {
          return (org.generic.UnauthenticatedUserRequest) request_;
        }
        return org.generic.UnauthenticatedUserRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 1) {
          return unauthenticatedBuilder_.getMessage();
        }
        return org.generic.UnauthenticatedUserRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
     */
    public Builder setUnauthenticated(org.generic.UnauthenticatedUserRequest value) {
      if (unauthenticatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        unauthenticatedBuilder_.setMessage(value);
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
     */
    public Builder setUnauthenticated(
        org.generic.UnauthenticatedUserRequest.Builder builderForValue) {
      if (unauthenticatedBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        unauthenticatedBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
     */
    public Builder mergeUnauthenticated(org.generic.UnauthenticatedUserRequest value) {
      if (unauthenticatedBuilder_ == null) {
        if (requestCase_ == 1 &&
            request_ != org.generic.UnauthenticatedUserRequest.getDefaultInstance()) {
          request_ = org.generic.UnauthenticatedUserRequest.newBuilder((org.generic.UnauthenticatedUserRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 1) {
          unauthenticatedBuilder_.mergeFrom(value);
        } else {
          unauthenticatedBuilder_.setMessage(value);
        }
      }
      requestCase_ = 1;
      return this;
    }
    /**
     * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
     */
    public Builder clearUnauthenticated() {
      if (unauthenticatedBuilder_ == null) {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 1) {
          requestCase_ = 0;
          request_ = null;
        }
        unauthenticatedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
     */
    public org.generic.UnauthenticatedUserRequest.Builder getUnauthenticatedBuilder() {
      return getUnauthenticatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
     */
    @java.lang.Override
    public org.generic.UnauthenticatedUserRequestOrBuilder getUnauthenticatedOrBuilder() {
      if ((requestCase_ == 1) && (unauthenticatedBuilder_ != null)) {
        return unauthenticatedBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 1) {
          return (org.generic.UnauthenticatedUserRequest) request_;
        }
        return org.generic.UnauthenticatedUserRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.generic.UnauthenticatedUserRequest, org.generic.UnauthenticatedUserRequest.Builder, org.generic.UnauthenticatedUserRequestOrBuilder> 
        getUnauthenticatedFieldBuilder() {
      if (unauthenticatedBuilder_ == null) {
        if (!(requestCase_ == 1)) {
          request_ = org.generic.UnauthenticatedUserRequest.getDefaultInstance();
        }
        unauthenticatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.generic.UnauthenticatedUserRequest, org.generic.UnauthenticatedUserRequest.Builder, org.generic.UnauthenticatedUserRequestOrBuilder>(
                (org.generic.UnauthenticatedUserRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 1;
      onChanged();;
      return unauthenticatedBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.generic.TokenIssueRequest.AuthenticatedUserRequest, org.generic.TokenIssueRequest.AuthenticatedUserRequest.Builder, org.generic.TokenIssueRequest.AuthenticatedUserRequestOrBuilder> authenticatedBuilder_;
    /**
     * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
     * @return Whether the authenticated field is set.
     */
    @java.lang.Override
    public boolean hasAuthenticated() {
      return requestCase_ == 2;
    }
    /**
     * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
     * @return The authenticated.
     */
    @java.lang.Override
    public org.generic.TokenIssueRequest.AuthenticatedUserRequest getAuthenticated() {
      if (authenticatedBuilder_ == null) {
        if (requestCase_ == 2) {
          return (org.generic.TokenIssueRequest.AuthenticatedUserRequest) request_;
        }
        return org.generic.TokenIssueRequest.AuthenticatedUserRequest.getDefaultInstance();
      } else {
        if (requestCase_ == 2) {
          return authenticatedBuilder_.getMessage();
        }
        return org.generic.TokenIssueRequest.AuthenticatedUserRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
     */
    public Builder setAuthenticated(org.generic.TokenIssueRequest.AuthenticatedUserRequest value) {
      if (authenticatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        request_ = value;
        onChanged();
      } else {
        authenticatedBuilder_.setMessage(value);
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
     */
    public Builder setAuthenticated(
        org.generic.TokenIssueRequest.AuthenticatedUserRequest.Builder builderForValue) {
      if (authenticatedBuilder_ == null) {
        request_ = builderForValue.build();
        onChanged();
      } else {
        authenticatedBuilder_.setMessage(builderForValue.build());
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
     */
    public Builder mergeAuthenticated(org.generic.TokenIssueRequest.AuthenticatedUserRequest value) {
      if (authenticatedBuilder_ == null) {
        if (requestCase_ == 2 &&
            request_ != org.generic.TokenIssueRequest.AuthenticatedUserRequest.getDefaultInstance()) {
          request_ = org.generic.TokenIssueRequest.AuthenticatedUserRequest.newBuilder((org.generic.TokenIssueRequest.AuthenticatedUserRequest) request_)
              .mergeFrom(value).buildPartial();
        } else {
          request_ = value;
        }
        onChanged();
      } else {
        if (requestCase_ == 2) {
          authenticatedBuilder_.mergeFrom(value);
        } else {
          authenticatedBuilder_.setMessage(value);
        }
      }
      requestCase_ = 2;
      return this;
    }
    /**
     * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
     */
    public Builder clearAuthenticated() {
      if (authenticatedBuilder_ == null) {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
          onChanged();
        }
      } else {
        if (requestCase_ == 2) {
          requestCase_ = 0;
          request_ = null;
        }
        authenticatedBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
     */
    public org.generic.TokenIssueRequest.AuthenticatedUserRequest.Builder getAuthenticatedBuilder() {
      return getAuthenticatedFieldBuilder().getBuilder();
    }
    /**
     * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
     */
    @java.lang.Override
    public org.generic.TokenIssueRequest.AuthenticatedUserRequestOrBuilder getAuthenticatedOrBuilder() {
      if ((requestCase_ == 2) && (authenticatedBuilder_ != null)) {
        return authenticatedBuilder_.getMessageOrBuilder();
      } else {
        if (requestCase_ == 2) {
          return (org.generic.TokenIssueRequest.AuthenticatedUserRequest) request_;
        }
        return org.generic.TokenIssueRequest.AuthenticatedUserRequest.getDefaultInstance();
      }
    }
    /**
     * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.generic.TokenIssueRequest.AuthenticatedUserRequest, org.generic.TokenIssueRequest.AuthenticatedUserRequest.Builder, org.generic.TokenIssueRequest.AuthenticatedUserRequestOrBuilder> 
        getAuthenticatedFieldBuilder() {
      if (authenticatedBuilder_ == null) {
        if (!(requestCase_ == 2)) {
          request_ = org.generic.TokenIssueRequest.AuthenticatedUserRequest.getDefaultInstance();
        }
        authenticatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.generic.TokenIssueRequest.AuthenticatedUserRequest, org.generic.TokenIssueRequest.AuthenticatedUserRequest.Builder, org.generic.TokenIssueRequest.AuthenticatedUserRequestOrBuilder>(
                (org.generic.TokenIssueRequest.AuthenticatedUserRequest) request_,
                getParentForChildren(),
                isClean());
        request_ = null;
      }
      requestCase_ = 2;
      onChanged();;
      return authenticatedBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TokenIssueRequest)
  }

  // @@protoc_insertion_point(class_scope:TokenIssueRequest)
  private static final org.generic.TokenIssueRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.generic.TokenIssueRequest();
  }

  public static org.generic.TokenIssueRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TokenIssueRequest>
      PARSER = new com.google.protobuf.AbstractParser<TokenIssueRequest>() {
    @java.lang.Override
    public TokenIssueRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TokenIssueRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TokenIssueRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.generic.TokenIssueRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

