// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package org.generic;

public interface TokenIssueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TokenIssueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
   * @return Whether the unauthenticated field is set.
   */
  boolean hasUnauthenticated();
  /**
   * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
   * @return The unauthenticated.
   */
  org.generic.UnauthenticatedUserRequest getUnauthenticated();
  /**
   * <code>.UnauthenticatedUserRequest unauthenticated = 1;</code>
   */
  org.generic.UnauthenticatedUserRequestOrBuilder getUnauthenticatedOrBuilder();

  /**
   * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
   * @return Whether the authenticated field is set.
   */
  boolean hasAuthenticated();
  /**
   * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
   * @return The authenticated.
   */
  org.generic.TokenIssueRequest.AuthenticatedUserRequest getAuthenticated();
  /**
   * <code>.TokenIssueRequest.AuthenticatedUserRequest authenticated = 2;</code>
   */
  org.generic.TokenIssueRequest.AuthenticatedUserRequestOrBuilder getAuthenticatedOrBuilder();

  public org.generic.TokenIssueRequest.RequestCase getRequestCase();
}
