// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package org.generic;

public interface UserValidityCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserValidityCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accessToken = 1;</code>
   * @return The accessToken.
   */
  java.lang.String getAccessToken();
  /**
   * <code>string accessToken = 1;</code>
   * @return The bytes for accessToken.
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();
}
