// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity.proto

package org.generic;

public interface UserValidityCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserValidityCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accessToken = 1;</code>
   * @return The accessToken.
   */
  java.lang.String getAccessToken();
  /**
   * <code>string accessToken = 1;</code>
   * @return The bytes for accessToken.
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <code>optional .Provider provider = 2;</code>
   * @return Whether the provider field is set.
   */
  boolean hasProvider();
  /**
   * <code>optional .Provider provider = 2;</code>
   * @return The enum numeric value on the wire for provider.
   */
  int getProviderValue();
  /**
   * <code>optional .Provider provider = 2;</code>
   * @return The provider.
   */
  org.generic.Provider getProvider();
}
