name: Authentication proto stub build

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  generate:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Install dependencies
          run: make

        - name: Commit and Push Changes
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            commit_message: "Automated commit from GitHub Action for protoc changes"
            branch: ${{ github.ref_name }}

  build:
    runs-on: ubuntu-latest
    needs: generate
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          server-id: github

      - name: Build with Maven
        run: mvn clean install
